# Generated by Django 4.0.6 on 2022-08-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='mode_preparo',
            new_name='modo_preparo',
        ),
    ]
